### ISSUE TITLE
Changing an addon to be hosted mode does not delete old ManifestWork

### ISSUE THREAD

**Issue by mprahl** [open-cluster-management-io/addon-framework#145]
If I define a `ManagedClusterAddOn` like this:

```yaml
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: config-policy-controller
  namespace: cluster2
spec:
  installNamespace: cluster2-grc
```

Then change it to hosted mode:

```yaml
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/hosting-cluster-name: cluster1
  name: config-policy-controller
  namespace: cluster2
spec:
  installNamespace: cluster2-grc
```

The `ManifestWork` for both deployment types remain:

```
❯ kubectl get manifestwork -A
NAMESPACE   NAME                                                       AGE
cluster1    addon-config-policy-controller-deploy-hosting-cluster2-0   3m18s
cluster2    addon-config-policy-controller-deploy-0                    10m
```
