### ISSUE TITLE
Support for using Cluster Labels in AddonTemplate

### ISSUE THREAD

**Issue by suresh-j2** [open-cluster-management-io/addon-framework#224]
As part of AddonTemplate, it would be great to have read the values from Cluster Labels. 

For example, if I set some hostname in managed cluster label, as part of addon manager, I can read that label key and use it while applying manifest.

This way, we can use the variable name and may be use cluster specific value also.

**Comment by zhujian7** [comment]
@suresh-j2 do you mean using variables in the addontemplates and getting the value from cluster labels, like this? 
```
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    region: us-east-1  # label
  name: cluster1
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
```
we want to use the label region in addonTemplate like:
```
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: my-addon-template
spec:
  addonName: my-addon
  agentSpec:
    workload:
      manifests:
      - apiVersion: v1
        kind: ConfigMap
        metadata:
          name: my-addon-configmap
        data:
          region: {{ region }} # or maybe {{ managedcluster.labels.region }}
```
