### ISSUE TITLE
the hosted addon is unavailable using Customized HealthCheck

### ISSUE THREAD

**Issue by zhiweiyin318** [open-cluster-management-io/addon-framework#314]
the hosted addon is unavailable using Customized HealthCheck 

```yaml
status:
  conditions:
  - lastTransitionTime: "2025-05-18T11:46:47Z"
    message: Addon manifestWork is not found
    reason: WorkNotFound
    status: Unknown
    type: Available
  healthCheck:
    mode: Customized
```
